# Generated by Django 5.2 on 2026-05-17 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('weight_kg', models.FloatField(verbose_name='Вес, кг')),
                ('volume_m3', models.FloatField(verbose_name='Объем, м³')),
                ('is_hazardous', models.BooleanField(default=False, verbose_name='Опасный груз')),
                ('requires_temperature', models.BooleanField(default=False, verbose_name='Требует температурный режим')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Номер заказа')),
                ('pickup_address', models.TextField(verbose_name='Адрес загрузки')),
                ('delivery_address', models.TextField(verbose_name='Адрес доставки')),
                ('waypoints', models.JSONField(blank=True, default=list, verbose_name='Промежуточные точки')),
                ('pickup_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время загрузки')),
                ('delivery_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок доставки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('loading', 'Загружается'), ('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('delayed', 'Задержан'), ('damaged', 'Поврежден')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimized_order', models.JSONField(default=list, verbose_name='Оптимальный порядок')),
                ('total_distance_km', models.FloatField(verbose_name='Расстояние, км')),
                ('algorithm_used', models.CharField(default='genetic', max_length=50, verbose_name='Алгоритм')),
                ('calculation_time_ms', models.FloatField(default=0.0, verbose_name='Время расчета, мс')),
                ('economy_percent', models.FloatField(default=0.0, verbose_name='Экономия, %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_routes', to='core.order')),
            ],
            options={
                'verbose_name': 'История маршрута',
                'verbose_name_plural': 'Истории маршрутов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Госномер')),
                ('type', models.CharField(choices=[('truck', 'Грузовик'), ('van', 'Фургон'), ('refrigerator', 'Рефрижератор')], max_length=20, verbose_name='Тип ТС')),
                ('capacity_kg', models.FloatField(verbose_name='Грузоподъемность, кг')),
                ('fuel_consumption', models.FloatField(verbose_name='Расход топлива, л/100км')),
                ('is_active', models.BooleanField(default=True, verbose_name='В эксплуатации')),
                ('current_driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle'),
        ),
    ]
