# Generated by Django 5.2 on 2026-05-20 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='core_order_status_6fe5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status'], name='core_order_client__a852eb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='core_order_created_912d27_idx'),
        ),
        migrations.AddIndex(
            model_name='routehistory',
            index=models.Index(fields=['order', 'created_at'], name='core_routeh_order_i_c8f17b_idx'),
        ),
        migrations.AddIndex(
            model_name='routehistory',
            index=models.Index(fields=['algorithm_used'], name='core_routeh_algorit_d4c68b_idx'),
        ),
    ]
