# Generated by Django 5.2 on 2026-05-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waypoints',
            field=models.JSONField(blank=True, default=list, verbose_name='Промежуточные точки'),
        ),
    ]
