# Generated by Django 5.2 on 2026-05-17 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance_km', models.FloatField(verbose_name='Общее расстояние, км')),
                ('estimated_time_min', models.IntegerField(verbose_name='Расчетное время, мин')),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Затраты на топливо, руб')),
                ('waypoints', models.JSONField(default=list, verbose_name='Путевые точки')),
                ('algorithm_used', models.CharField(default='genetic', max_length=50, verbose_name='Использованный алгоритм')),
                ('optimization_score', models.FloatField(default=0.0, verbose_name='Оценка оптимизации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='core.order')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicle')),
            ],
        ),
    ]
